### PR TITLE
The location, where file is saved is not right

### LINKED ISSUE #405: The location, where file is saved is not right
While saving files, if the location, where the file should be saved changes, the file is not saved to the selected directory.
It is saved to the directory above with the directoryname as filename. A little example:

I want to save to D:\scores\myscore\score.mxml, so I navigate to this directory with the save file dialog.
When I press save the file is saved in D:\scores\myscore.mxml

(Because the filename is not seperated from the file path)

### PR DESCRIPTION
**Pull request by NelDav**
closes #405

### CODE REVIEW

**Comment by NelDav** [comment]
I implemented a first quick and dirty workaround for the `Save as` option.
I think it would be better, if the filname is separated from the path inside the JFileChooser.

Example:
grafik
instead of
grafik

**Comment by NelDav** [comment]
After some further research, I think the way to go is to prevent the `JFileChooser` to update the File Name when changing the directory.

**Comment by NelDav** [comment]
A little summary:
In this PR the selection mode from 'JFileChooser' is changed from 'FILES_AND_DIRECTORIES' to 'FILES_ONLY'. Therefore the filename of the 'JFileChooser' doesn't change if the user changes the directory. I think that is a acceptable solution because I did not find any use of the 'JFileChooser' where a directory needs to be selected. In case this feature is needed anyway in my opinion the best way would be to create a 'directoryChooser' function next to the 'fileChooser'.

The second implemented feature is, the method 'removePrintExtension'. This method checks, if the extension of a path is '-print.pdf'. If the path ends with this string, the extension is removed. This method is implemented to create the same behavior for the _print_ feature, as it is already implemented for the _export_ and the _save_ features.

**Comment by hbitteur** [comment]
I think I'm beginning to understand your concern. 
I will get back to you within 2 days (I'm away from home)

**Comment by hbitteur** [comment]
I have serious difficulties to compare your PR with current code.
We never develop in master branch, but in development branch (which is merged to master only at release time).
For us, "current" code is code in development branch.
Could you base your PR on development branch version instead? (the master code is 5.1, many many months old).

**Comment by NelDav** [comment]
I searched for a developer guide before but I didn't found it. I did not expect that there is a Wiki page. That is the first Wiki page I have ever seen on GitHub. I thought wiki pages are only a feature of GitLab.

As you suggestet, I merged the developer branch into this branch and now I understand, why we are talking at cross purpose. The Issue is fixed since commit 2d271de367c050d5e51ff5dde9c4ffa6372ebf67. I will close this PR and Issue #405.

**Pull request closed without merging**
