### PR TITLE
fix newFileSystem

### PR DESCRIPTION
**Pull request by balping**
Resolves ambiguity

More info: https://bugs.openjdk.java.net/browse/JDK-8223197

### CODE REVIEW

**Comment by hbitteur** [comment]
@balping 
Could you check with current code status (in "development" branch), which is meant to be compatible with Java11.

For Book class, line 2600, we have:
`FileSystem fileSystem = FileSystems.newFileSystem(bookPath, (ClassLoader) null);`

For ZipFileSystem class, line 103, we also have:
`FileSystem fileSystem = FileSystems.newFileSystem(path, (ClassLoader) null);`

The explicit cast is here to avoid method ambiguity.
And the "java11" branch has been merged with "development" branch. We should now delete this java11 branch, I need to check with Maxim who created it.

If I understand correctly your comment, a new method "newFileSystem" exists with just one parameter (of type Path) in Java 13. But it does not exist in Java 11.

The current target for development branch (and for the 5.2 release we plan to release ASAP) is Java 11. We cannot introduce modifications that would not be compatible with Java 11.

Please tell me if misunderstood something.

**Comment by hbitteur** [comment]
@maximumspatium 
Could we delete this branch, now that we've moved to Java 17?

**Comment by maximumspatium** [comment]
> Could we delete this branch, now that we've moved to Java 17?

@hbitteur Do you mean closing this PR (pull request)?

**Comment by hbitteur** [comment]
@maximumspatium 
No, I meant the java11 branch, as it can be seen on [https://github.com/Audiveris/audiveris/branches](https://github.com/Audiveris/audiveris/branches)

**Comment by maximumspatium** [comment]
Feel free to delete it if you aren't going to merge it.

**Pull request closed without merging**
