### PR TITLE
Add option for disabling book indents

### PR DESCRIPTION
**Pull request by larrabee**
Hello.
This PR related to issue #250  
Added flag `org.audiveris.omr.sheet.SystemManager.disableIndents` which disables scores auto splitting.  
Thanks for the great tool.

### CODE REVIEW

**Comment by hbitteur** [comment]
Thanks @larrabee for your contribution.

On top of your implementation, I propose to add this flag in the so-called Book Parameters, accessed from "Book | Set Parameters..." pulldown menu. The related dialog allows you to set this kind of flag for various scopes: for any book, for a specific book or for a specific sheet.

This will use your implementation, and wrap it in a user-friendly way to set/unset the low-level application constant.

**Comment by hbitteur** [comment]
I got a problem trying to merge your PR.

I'm not a Git guru, but I think this is related to the fact that, on Audiveris project, we do not develop directly in master branch, but rather in development branch (or a temporary sub-branch thereof). See our workflow [Wiki description](https://github.com/Audiveris/audiveris/wiki/Git-Workflow).
We merge development to master only at release time.

As an exception to this "rule", in order to take advantage of GitGub Pages, documentation iis being developed in /docs folder of master branch.

I tried to merge your PR (from master branch of a fork, if I understand correctly) to my development branch, but then I got 100+ modified documentation files pulled at the same time (from master to development) plus a conflict with a couple of Java classes.

Since your modification is a small number of modified lines in SystemManager class, I propose to include them manually in the current development branch, and then proceed to the augmentation of Book Parameters dialog I told you about in my previous message.
Doing so, this new feature will be available immediately in development branch as all the other new features and later merged into master branch when 5.2 release is out (a matter of a few weeks).

There might be smarter ways to cope with this but, like I said, I'm far from fully mastering Git.

Would this be OK for you?

**Comment by larrabee** [comment]
Hello.  
Thanks for quick response.
>> On top of your implementation, I propose to add this flag in the so-called Book Parameters, accessed from "Book | Set Parameters..." pulldown menu. The related dialog allows you to set this kind of flag for various scopes: for any book, for a specific book or for a specific sheet.  

Im not a Java developer, but i will try to add this;)

>> Would this be OK for you?  

Yes, that will be good.

**Comment by hbitteur** [comment]
If you're not a Java developer, don't waste your time fighting with the book parameters dialog. I'll take care of this (but still give you credit for your feature! :-))

**Comment by hbitteur** [comment]
Done in commit f54093828c7c991a81ffb6ca37b0dc715c79b349 on development branch

**Comment by larrabee** [comment]
Thank you;)

**Pull request closed without merging**
