### PR TITLE
Add travis support

### PR DESCRIPTION
**Pull request by mercuriete**
1) Create java/gradle configuration
2) install tesseract as build dependency
3) add Xvfb because some test needs X server

### CODE REVIEW

**Comment by mercuriete** [comment]
Hi auidiveris developers.

I created a travis config file to add travis continous integration.
It pass all tests.

If you don't have travis account, is free for open source projects.
I hope you like this pull request.

**Comment by mercuriete** [comment]
ping? @maximumspatium

**Comment by maximumspatium** [comment]
@mercuriete Your patch looks good. The only thing is that new features shouldn't be merged directly into the master branch but into the development branch instead, see [our workflow description](https://github.com/Audiveris/audiveris/wiki/Git-Workflow).

Would you kindly rebase your patch to incorporate the latest audiveris changes and create a pull request against `audiveris:development` ? Thank you!

**Comment by maximumspatium** [comment]
Manually rebased and merged into audiveris/travis-ci, see https://github.com/Audiveris/audiveris/commit/1fd4d05052dbb34fc42ab21e642da82d37fa0335

Thank you for your contribution!

**Comment by mercuriete** [comment]
Sorry for not reading the documentation!

Thanks you for merge the patch.

:)

**Pull request closed without merging**
