### PR TITLE
Added support for linux-arm64.

### PR DESCRIPTION
**Pull request by inouehiroo**
Upgraded Tesseract, Leptonica and Javacpp.

### CODE REVIEW

**Comment by hbitteur** [comment]
@inouehiroo 
I just pulled and built your PR.
When I tried to run it (I'm under Windows), I immediately got the following stack dump:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path: C:\Program Files\Java\jdk-17.0.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.0.10-Q16;c:/Program Files/Java/jdk-17.0.2\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\prog\Python35\Scripts\;D:\prog\Python35\;C:\ProgramData\Oracle\Java\javapath;c:\cygwin64\bin;d:\prog\apache-maven-3.8.4\bin;D:\prog\gradle-4.10.2\bin;D:\prog\Perl\site\bin;D:\prog\Perl\bin;D:\prog\Umlet;D:\prog\util;d:\prog\apache-ant-1.9.3\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Meld\meld\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Tesseract-OCR;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\herve\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;D:\prog\libxslt-1.1.26.win32\bin;D:\prog\libxml2-2.7.8.win32\bin;D:\prog\zlib-1.2.5\bin;D:\prog\iconv-1.9.2.win32\bin;C:\Program Files\Graphviz\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\ClockworkMod\Universal Adb Driver;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\dotnet\;C:\Program Files\GitHub CLI\;C:\Ruby26-x64\bin;C:\Users\herve\AppData\Local\Tesseract-OCR;C:\Users\herve\AppData\Local\Microsoft\WindowsApps;C:\Users\herve\AppData\Local\GitHubDesktop\bin;C:\Users\herve\AppData\Local\Microsoft\WindowsApps;C:\Users\herve\AppData\Local\atom\bin;C:\Users\herve\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\herve\AppData\Roaming\npm;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin;;.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1800)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1402)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.leptonica.global.lept.<clinit>(lept.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1269)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.tesseract.TessBaseAPI.<clinit>(TessBaseAPI.java:26)
	at org.audiveris.omr.text.tesseract.TesseractOCR.identify(TesseractOCR.java:155)
	at org.audiveris.omr.Main.showEnvironment(Main.java:415)
	at org.audiveris.omr.Main.main(Main.java:126)
	at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jnilept in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1767)
	... 14 more
```
I noticed in your modified version of `build.gradle` file that all references to leptonica have been removed, this can explain the unability to find `jnilept` at run time.

Could you elaborate on this removal? I suppose it works for Linux, but not for Windows. And for MacOS I can't tell.

Thanks in advance for your help.
/Hervé

**Comment by hbitteur** [comment]
Also, what is the motivation for removing JavaCPP?
Sorry, I don't master these bridges between Java and C++.
Please explain this to me.
/Hervé

**Comment by inouehiroo** [comment]
Javacpp, Leptonica was already included in the pom.xml of Tesseract, so I figured I could remove it and the build on Debian on Raspberry Pi 4 B was successful. It seems like an OS specific issue perhaps, but I will revert this part. Thanks.

https://github.com/bytedeco/javacpp-presets/blob/1.5.7/tesseract/pom.xml

**Comment by maximumspatium** [comment]
Thank you for submitting this PR!
It looks like our works crossed - I recently switched Audiveris to Tesseract 4.1.1 and Javacpp-presets 1.5.6, see https://github.com/Audiveris/audiveris/commit/ce976106850aded17558af14116d5d89c54e37a4

Would you mind pulling the above changes, adding this single line that extends the list of supported architectures, testing the changes in your arm64 machine and submitting a new PR? I'd greatly appreciate your effort!

Please don't upgrade to Tesseract 5 yet! Doing so would break support for Mac OS < 10.15. Thank you again.

**Comment by hbitteur** [comment]
@inouehiroo 
Many thanks for your contribution, but several conflicting modifications are happening in parallel and we have to sort them out.
Please pull @maximumspatium's modifications, then add your own extension to linux-arm64 and finally submit the result as a new PR.
Thanks
/Hervé

**Comment by inouehiroo** [comment]
In my environment with Debian(testing) on a Raspberry Pi 4 B, it builds and runs successfully without any problems.

**Comment by maximumspatium** [comment]
@inouehiroo Github tolling tells: `This branch cannot be rebased due to conflicts`.
I believe that's because you've merged changes from the `origin/tess4` branch. Unfortunately, this branch has diverged too much from the `development` branch.
Would you mind rebasing your changes onto the `development` branch? All changes related to Tesseract 4 are already there.
Thank you in advance!

**Comment by maximumspatium** [comment]
Merged. Thank you a lot!

**Comment by inouehiroo** [comment]
Thank you too.

**Comment by Altonss** [comment]
That's great, thank you :)

**Pull request merged**
