### PR TITLE
Binarization adjustment board 

### PR DESCRIPTION
**Pull request by mgporter**
Hi all! As a musician and programmer, Audiveris is a really exciting program for me. I have been trying to get to know Audiveris's codebase so that I can contribute to it more in the future. For now, I just wanted to start by doing something simple. 

I created a board that allows the user to adjust image binarization settings and change binarization filters before going on to the OMR step. I thought this would be easier for new users, so that they don't have to dig around for these settings. This "BinarizationAdjustBoard" is added and selected by default on the binary tab only.

BinarizationAdjustBoard

### CODE REVIEW

**Comment by hbitteur** [comment]
Hi Michael,

Your approach is more convenient than the current binarization section in the book parameters.
It's easy to use and we can observe the impact immediately when a parameter is modified.
I like it.

I suppose we can now remove the binarization section in the book parameters.
No big deal but I won't have time to do it before a few days. You can also take care of this on your own if you wish, just tell me.

Thanks,
/Hervé

**Comment by mgporter** [comment]
Thank you Hervé for your encouragement! I can make that change in the book parameters. Now off to fix some bugs!

**Comment by hbitteur** [comment]
Hi Michael,

We have a problem with the BinarizationAdjustBoard  automatically added to the Binary tab.
- In the normal case it works: the input image is read, converted to gray, and then fed into the binarization filter.
- But in a .omr file, the binary data of a sheet is kept as a local BINARY.png file within the .omr zip archive. When trying to display the binary view, the BinarizationAdjustBoard now tries to connect to some gray material (and for that tries to fetch the original input file, which may no longer be available...)

We should be protected against this, because we often want to simply have a look at the binary image (for instance to compare with the transcription results), without re-launching any binarization process of course.

```
WARN  []               BookActions 452  | Error in displayBinary java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getColorModel()" because "img" is null
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getColorModel()" because "img" is null
	at org.audiveris.omr.sheet.Picture.adjustImageFormat(Picture.java:1128)
	at org.audiveris.omr.sheet.Picture.getGrayImage(Picture.java:536)
	at org.audiveris.omr.sheet.Picture.getSource(Picture.java:643)
	at org.audiveris.omr.step.BinaryStep.runBinarizationFilter(BinaryStep.java:118)
	at org.audiveris.omr.sheet.ui.BinarizationAdjustBoard.runBinarizationFilter(BinarizationAdjustBoard.java:292)
	at org.audiveris.omr.sheet.ui.BinarizationAdjustBoard.connect(BinarizationAdjustBoard.java:314)
	at org.audiveris.omr.ui.Board.setSelected(Board.java:479)
	at org.audiveris.omr.sheet.Sheet.createBinaryView(Sheet.java:597)
	at org.audiveris.omr.sheet.ui.BookActions.displayBinary(BookActions.java:444)
```

For the time being, I have simply commented out the line 597 in Sheet.java:
```
///baBoard.setSelected(true);
```
And I avoid to manually select the BinarizationAdjustBoard when I don't have the original source file!
But this is just a workaround...

**Comment by mgporter** [comment]
Thank you for the detailed writeup Hervé! I should learn more about how your program functions in different situations. I'll look at how your program currently handles this and see if there is a good solution.

**Comment by hbitteur** [comment]
While you are at it, the label "Apply to all _pages_" would be better named "Apply to all _sheets_".
Because what we binarize is a (physical) sheet, not any (logical) page yet.
See [this section](https://audiveris.github.io/audiveris/_pages/main/score_page/) in the handbook for an explanation of sheets vs pages.

**Comment by hbitteur** [comment]
Also, I noticed this line in the connect() method of BinarizationAdjustBoard, right after the comment
`// Re-binarize image if the filter has changed`

```
        if (sheet.getStub().getBinarizationFilter() != previousFilter) {
```
This is dangerous because it checks if the 2 items have the same _address_, while we just want to compare their _values_.
And actually, the addresses are different, hence the filter is always re-applied. Bad luck!

The line should be replaced by:
``` 
       if (!sheet.getStub().getBinarizationFilter().equals(previousFilter)) {
```
And indeed the filter is no longer re-applied if not modified in value.

This prevents the raise of exception when the input file is no longer available (see the previous message)

We could even keep the pre-selection of the BinarizationAdjustBoard (the line: `baBoard.setSelected(true);`)
But the user should not press any of the buttons (Apply, Reset, ...). Not very user-friendly! :-)

Perhaps the BinarizationAdjustBoard should be "selectable" (automatically or on demand) **only if** the input file has been successfully checked for availability beforehand.
What do you think of this approach?

**Pull request merged**
